on:
  push:
    branches:
      - master
    tags:
      - v2
      - v1*   
  label:
    types: 
      - created

jobs:
  print_hello:       
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
